config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts,          only: [:create, :destroy, :update]
  resources :topics,         only: [:create, :destroy, :update]
  resources :forums,         only: [:create, :destroy, :update]

  get    'forums' => 'forums#show', as: 'forums_show'
  get    'forum/:id/topics' => 'topics#show', as: 'topics_show'
  get    'forum/:forum_id/topic/:topic_id' => 'posts#show', as: 'posts_show'
  get    'forum/:id/topics/new'  => 'topics#new', as: 'new_topic'
  get    'forum/new'  => 'forums#new', as: 'new_forum'

end

app/models/forum.rb
class Forum < ActiveRecord::Base
  has_many :topics, dependent: :destroy
  has_many :posts, through: :topics, dependent: :destroy

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController
  before_action :logged_in_user, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :admin_user,     only: [:new, :create, :edit, :update, :destroy]

  def show
    @forums = Forum.includes(:topics).order(:created_at).paginate(page: params[:page], per_page: 10)
  end

  def new
    @forum = Forum.new
  end

  def create
    @forum = Forum.new(forum_params)
    if @forum.save
      flash[:success] = "Forum created"
      redirect_to forums_show_path
    else
      render 'new'
    end
  end

  def destroy
    forum_to_delete = Forum.find(params[:id])

    if forum_to_delete.topics
      forum_to_delete.topics.each do |t|
        t.update_attributes(:last_post => nil)
        t.destroy
      end
    end

    forum_to_delete.destroy
    flash[:success] = "Forum deleted"
    redirect_to forums_show_path
  end

  def update
    @forum = Forum.find(params[:id])
    if @forum.update_attributes(forum_params)
      flash[:success] = "Forum title updated"
      redirect_to forums_show_path
    else
      flash[:danger] = "Forum title not updated - title invalid (minimum length 3, maximum 100)"
      redirect_to forums_show_path
    end
  end

  private

    def forum_params
      params.require(:forum).permit(:title)
    end

end

app/helpers/forums_helper.rb
module ForumsHelper

end

app/views/forums/_forum.html.erb
<% if @forums.any? %>
  <% @forums.each do |f| %>
    <tr>
      <td class="col-md-10">
          <p><%= link_to f.title, "forums/#{f.id}"
              %></p>
          <p>Topics: <%= f.topics.count %>, 
            Posts: <%= f.posts.count %></p>
      </td>

      <td class="col-md-2">
        <% if !f.topics.empty? %>
          <p data-toggle="tooltip" title="<%= f.topics.order("last_post_id")
            .last.title %>">
            <%= truncate(f.topics.order("last_post_id").last.title, :length => 30) %>
          </p>
          <p><%= f.topics.order("last_post_id").last.posts.first.user.name %>, 
            <%= time_ago_in_words(f.topics.order("last_post_id")
               .last.posts.first.created_at)%> ago</p>
        <% else %>
          <p>No topics in this forum</p>
        <% end %>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/forums/_forum_new.html.erb
<%= form_for(@forum) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

<%= f.submit "Create Forum", class: "btn btn-primary", data: { disable_with: 'Submitting...' } %>
<% end %>

app/views/forums/_forum_topics.html.erb
<% if @topics.any? %>
  <% @topics.each do |f| %>
    <tr>
      <td class="col-md-9">
        <p><%= link_to word_wrap(f.title), 
          "../topics/#{f.id}" %></p>
          <p>By: <%= f.last_post.user.name %> at 
          <%= f.last_post.created_at.to_formatted_s(:db) %>, 
          Posts: <%= f.posts.count %></p>
      </td>
      <td class="col-md-1">
        <% if current_user.admin? || current_user?(f.last_post.user) %>

          <button id="Modal_<%= f.id %>" type="button" class="btn btn-primary btn-xs" 
            data-toggle="modal" data-target="#myModal_<%= f.id %>">
            <span class="glyphicon glyphicon-edit"></span>
          </button>

          <div class="modal fade" id="myModal_<%= f.id %>" role="dialog">
            <div class="vertical-alignment-helper">
            <div class="modal-dialog vertical-align-center"> 
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Edit Topic Title</h4>
                </div>
                <div class="modal-body">
                  <%= form_tag topic_path(f.id), :method => :patch do %>
                    <%= text_field_tag "title", f.title %>
                    <%= submit_tag "Submit", class: "btn btn-primary" %>
                  <% end %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
              </div>
            </div>
            </div>
          </div>

          <%= link_to f, method: :delete, 
            data: { confirm: "You sure?" }, class: "btn btn-primary btn-xs" do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        <% end %>
      </td>
      <td class="col-md-2">
        <p>Last Post By: <%= truncate(f.last_post.user.name, :length => 30) %></p>
        <p><%= time_ago_in_words(f.last_post.created_at) %> ago</p>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/forums/_forums.html.erb
<% if @forums.any? %>
  <% @forums.each do |f| %>
    <tr>
      <td class="col-md-9">
          <p class="<%= f.id %>.title"><%= link_to f.title, 
            topics_show_path(f.id) %>
          </p>
          <p class="<%= f.id %>.info">
            Topics: <%= f.topics.count %>, Posts: <%= f.posts.count %>
          </p>
      </td>
      <td class="col-md-1">
        <% if current_user.admin? %>

          <button id="Modal_<%= f.id %>" type="button" class="btn btn-primary btn-xs" 
            data-toggle="modal" data-target="#myModal_<%= f.id %>">
            <span class="glyphicon glyphicon-edit"></span>
          </button>

          <div class="modal fade" id="myModal_<%= f.id %>" role="dialog">
            <div class="vertical-alignment-helper">
            <div class="modal-dialog vertical-align-center"> 
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Edit Forum Title</h4>
                </div>
                <div class="modal-body">
                  <%= form_tag forum_path(f.id), :method => :patch do %>
                    <%= text_field_tag "title", f.title %>
                    <%= submit_tag "Submit", class: "btn btn-primary" %>
                  <% end %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
              </div>
            </div>
            </div>
          </div>

          <%= link_to f, method: :delete, 
            data: { confirm: "Are you sure?" }, class: "btn btn-primary btn-xs" do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        <% end %>
      </td>
      <td class="col-md-2 table-border">
        <% if !f.topics.empty? %>
          <p class="<%= f.id %>.latest_topic" data-toggle="tooltip" 
            title="<%= f.topics.order("last_post_id").last.title %>">
            <%= link_to truncate(f.topics.order("last_post_id").last.title, 
              :length => 30), posts_show_path(forum_id: f.id, 
              topic_id: f.topics.order("last_post_id").last.id) %>
          </p>
          <p class="<%= f.id %>.latest_user" data-toggle="tooltip" 
            title="<%= f.topics.order("last_post_id").
            last.posts.first.user.name %>">
            <%= link_to truncate(f.topics.order("last_post_id").last.posts.
              first.user.name, :length => 12), f.topics.order("last_post_id").
              last.posts.first.user %>, <%= time_ago_in_words(f.topics.
              order("last_post_id").last.posts.first.created_at) %> ago</p>
        <% else %>
          <p class="<%= f.id %>.no_topics">No topics in this forum</p>
        <% end %>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/forums/new.html.erb
<% provide(:title, 'New Forum') %>
<% provide(:button_text, 'Create forum') %>
<h1>New Forum</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'forum_new' %>
  </div>
</div>

app/views/forums/show.html.erb
<div class="container-fluid">
  <ol class="breadcrumb">
    <li><%= link_to "Forums Home", forums_show_path %></li>
  </ol>
  <div>
    <% if current_user.admin? %>
      <%= link_to "Create a new forum!", new_forum_path, 
        {class: "btn btn-sm btn-primary", style: "float:left"} %>
    <% end %>
  </div>
  <div class="custom_pagination">
    <%= will_paginate @forums, :inner_window => 1, :outer_window => 0 %>
  </div>
  <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th class="col-md-9">Forum</th>
            <th class="col-md-1"></th>
            <th class="col-md-2 table-title-border">Latest</th>
          </tr>
        </thead>
        <tbody>
          <ol>
            <%= render 'forums' %>
          </ol>
        </tbody>
      </table>
  </div>
  <div class="custom_pagination">
    <%= will_paginate @forums, :inner_window => 1, :outer_window => 0  %>
  </div>
</div>