config/routes.rb
Rails.application.routes.draw do
  root                'static_pages#home'
  get    'help'    => 'static_pages#help'
  get    'about'   => 'static_pages#about'
  get    'contact' => 'static_pages#contact'
  get    'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :posts,          only: [:create, :destroy, :update]
  resources :topics,         only: [:create, :destroy, :update]
  resources :forums,         only: [:create, :destroy, :update]

  get    'forums' => 'forums#show', as: 'forums_show'
  get    'forum/:id/topics' => 'topics#show', as: 'topics_show'
  get    'forum/:forum_id/topic/:topic_id' => 'posts#show', as: 'posts_show'
  get    'forum/:id/topics/new'  => 'topics#new', as: 'new_topic'
  get    'forum/new'  => 'forums#new', as: 'new_forum'

end

app/models/topic.rb
class Topic < ActiveRecord::Base
  belongs_to :forum
  has_many :posts, dependent: :destroy
  has_many :users, through: :posts
  belongs_to :last_post, class_name: "Post", foreign_key: "last_post_id"

  attr_accessor :last_post_id

  validates :title, presence: true, length: { minimum: 3, maximum: 100 }
  validates :first_post_content, presence: true, length: { minimum: 3, maximum: 1000 }
  validates :forum_id, presence: true
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  before_action :logged_in_user, only: [:show, :new, :create, :edit, :update, :destroy]
  before_action :correct_user_or_admin_topic,   only: [:edit, :update, :destroy]

  def show
    @current_forum = Forum.find(params[:id])

    @topics = Topic.includes(:last_post, :posts).where(forum_id: params[:id])
                .order("last_post_id").reverse
                .paginate(page: params[:page], per_page: 10)
  end

  def new
    @forum_id = Forum.find(params["id"]).id
    @topic = Forum.find(params["id"]).topics.build
  end

  def create
    @forum_id = Forum.find(params["topic"]["forum_id"]).id
    @topic = Forum.find(params["topic"]["forum_id"]).topics.build(topic_params)

    if @topic.save
      @post = current_user.posts.where(topic_id: @topic.id).build(
         content: @topic.first_post_content)
      @post.save
      @topic.update_columns(last_post_id: @post.id)
      flash[:success] = "Topic and first post created!"
      redirect_to topics_show_path(@forum_id)
    else
      render 'new'
    end
  end

  def destroy
    topic_to_delete = Topic.find(params[:id])
    topic_to_delete.update_attributes(:last_post => nil)
    topic_to_delete.destroy
    flash[:success] = "Topic deleted"
    redirect_to topics_show_path(topic_to_delete.forum.id)
  end

  def update
    @topic = Topic.find(params[:id])
    if @topic.update_attributes(topic_params)
      flash[:success] = "Topic updated"
      redirect_to topics_show_path(@topic.forum.id)
    else
      flash[:danger] = "Topic not updated - title invalid (minimum length 3, maximum 100)"
      redirect_to topics_show_path(@topic.forum.id)
    end
  end

  private

    def topic_params
      params.require(:topic).permit(:title, :first_post_content, :forum_id)
    end

end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/topics/_forum_topics.html.erb
<% if @topics.any? %>
  <% @topics.each do |f| %>
    <tr>
      <td class="col-md-9">
        <p class="<%= f.id %>.title"><%= link_to word_wrap(f.title), 
          posts_show_path(forum_id: f.forum.id, topic_id: f.id) %></p>
          <p class="<%= f.id %>.info">By: <%= link_to f.posts.last.user.name, 
            f.posts.last.user %>, <%= time_ago_in_words(f.posts.last
            .created_at) %> ago. Posts: <%= f.posts.count %>
          </p>
      </td>
      <td class="col-md-1">
        <% if current_user.admin? || current_user?(f.posts.last.user) %>

          <button id="Modal_<%= f.id %>" type="button" class="btn btn-primary btn-xs" 
            data-toggle="modal" data-target="#myModal_<%= f.id %>">
            <span class="glyphicon glyphicon-edit"></span>
          </button>

          <div class="modal fade" id="myModal_<%= f.id %>" role="dialog">
            <div class="vertical-alignment-helper">
            <div class="modal-dialog vertical-align-center"> 
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h4 class="modal-title">Edit Topic Title</h4>
                </div>
                <div class="modal-body">
                  <%= form_tag topic_path(f.id), :method => :patch do %>
                    <%= text_field_tag "title", f.title %>
                    <%= submit_tag "Submit", class: "btn btn-primary" %>
                  <% end %>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
                </div>
              </div>
            </div>
            </div>
          </div>

          <%= link_to f, method: :delete, 
            data: { confirm: "Are you sure?" }, class: "btn btn-primary btn-xs" do %>
            <span class="glyphicon glyphicon-trash"></span>
          <% end %>
        <% end %>
      </td>
      <td class="col-md-2 table-border">
        <p class="<%= f.id %>.latest_post">Last Post By: <%= link_to truncate(f.last_post.user.name, 
          :length => 30), f.last_post.user %></p>
        <p class="<%= f.id %>.latest_time"><%= time_ago_in_words(f.last_post.created_at) %> ago</p>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/topics/_topic_new.html.erb
<%= form_for(@topic) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>

  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>

  <%= f.label "Post" %>
  <%= f.text_area :first_post_content, placeholder: "Compose first post...", class: 'form-control' %>

  <%= f.hidden_field :forum_id, :value => @forum_id %>

<%= f.submit "Create Topic", class: "btn btn-primary", data: { disable_with: 'Submitting...' } %>
<% end %>

app/views/topics/new.html.erb
<% provide(:title, 'New Topic') %>
<% provide(:button_text, 'Create topic') %>
<h1>New Topic</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'topic_new' %>
  </div>
</div>

app/views/topics/show.html.erb
<% if logged_in? %>
<% provide(:title, "#{@current_forum.title}") %>

<div class="container-fluid">
  <ol class="breadcrumb">
    <li><%= link_to "Forums Home", forums_show_path %></li>
    <li><%= link_to @current_forum.title,
      topics_show_path(@current_forum.id) %></li>
  </ol>

  <div>
    <%= link_to "Create a new topic!", new_topic_path(@current_forum.id), 
      {class: "btn btn-sm btn-primary", style: "float:left"} %>
  </div>
  <div class="custom_pagination">
    <%= will_paginate @topics, :inner_window => 1, :outer_window => 0  %>
  </div>

  <div class="table-responsive">
      <table class="table table-striped">
        <thead>
          <tr>
            <th class="col-md-7">Topic</th>
            <th class="col-md-1"></th>
            <th class="col-md-4 table-title-border">Latest</th>
          </tr>
        </thead>
        <tbody>
          <%= render 'forum_topics' %>
        </tbody>
      </table>
  </div>
  <div class="custom_pagination">
    <%= will_paginate @topics, :inner_window => 1, :outer_window => 0 %>
  </div>
</div>

<% end %>